//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcousticSystems.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int ID { get; set; }
        public string Image { get; set; }
        public string Name { get; set; }
        public int Brand { get; set; }
        public int Model { get; set; }
        public decimal Price { get; set; }
        public string AmountInStock { get; set; }
        public string Description { get; set; }
        public int IDClient { get; set; }
        public System.DateTime OrderDate { get; set; }
    
        public virtual Brands Brands { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual Models Models { get; set; }
    }
}
